### ISSUE TITLE
2P模式看爱奇艺时好时坏

### ISSUE THREAD

**Issue by edison0354** [daiyeqi/bilibili_hkj#2]
反正就是有时候可用，有时候就是黑底白字提示视频已删除，但是爪机客户端是可以播放的

**Comment by daiyeqi** [comment]
爱奇艺没办法 你挂代理试试吧

**Comment by edison0354** [comment]
感谢回复！
不过现在网页版已经彻底不给显示入口了，2P模式直接没法用了……囧……
