### ISSUE TITLE
youku视频无法获取神秘代码

### ISSUE THREAD

**Issue by lan23333** [daiyeqi/bilibili_hkj#3]
神秘代码我记得好像是CID？我看星刻的龙骑士的时候，黑科技会提示无法获取神秘代码

我看了看HTML里面的flashvar是

bili-cid=1592321&amp;url=http%3A%2F%2Fplayer.youku.com%2Fplayer.php%2FType%2FFolder%2FFid%2F0%2Fsid%2FXNzA2MzAxMTIw%2Fv.swf

是不是因为缺少aid的原因？

**Comment by daiyeqi** [comment]
应该是星刻的龙骑士返回的数据YQL无法解析导致的吧. 有空找找 YQL 的代替品
