### ISSUE TITLE
README也太简陋了吧。看名字完全不知道是做神马的啊。

### ISSUE THREAD

**Issue by qiansen1386** [daiyeqi/bilibili_hkj#4]
话说原理是什么？Bilibili API？

**Comment by MAGI-Yang** [comment]
大概是用js在其它视频源上套个B站播放器
其实B站本身只是在其他视频源上面套自己的播放器而已.....
当然，我不懂js

在 2014年5月15日，下午6:07，东方孤思子（Paris·QianSen） notifications@github.com 写道：

**Comment by qiansen1386** [comment]
现在支持哪些站点呢？

在 2014年5月15日 下午6:15，MAGI-Yang notifications@github.com写道：

> 大概是用js在其它视频源上套个B站播放器
> 其实B站本身只是在其他视频源上面套自己的播放器而已.....
> 当然，我不懂js
> 
> 在 2014年5月15日，下午6:07，东方孤思子（Paris·QianSen） notifications@github.com 写道：
> 
> > 话说原理是什么？Bilibili API？
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/keyfunc/bilibili_hkj/issues/4#issuecomment-43192479
> .

## 

Regards,
Paris Qian Sen
